name: Build Sandy BG APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libltdl-dev libffi-dev libssl-dev autoconf automake libtool pkg-config cmake git openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer cython==0.29.33 kivy

    - name: Build APK with Buildozer
      run: |
        yes | buildozer -v android debug

    - name: Upload APK Artifact
      ses: actions/upload-artifact@v4
      with:
        name: Sandy-BG-APK
        path: bin/*.apk
